<a href="https://colab.research.google.com/github/matsu1730/checkpoint-1-iot-iob-ia/blob/main/checkpoint_1_iot.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [331]:
# importando dataset

import pandas as pd
import numpy as np

df = pd.read_csv('/content/breast-cancer-random-csv.txt')
df.head(1)

classe    age menopause tumorsize invnodes nodecaps  degmalig  \
0  recurrence-events  50-59   premeno     30-34      0-2       no         3   

  breast breastquad irradiant  
0  right    left_up       yes

In [332]:
# separando colunas que vamos utilizar

df = df[["classe",
         "age",
         "menopause",
         "tumorsize",
         "invnodes",
         "degmalig",
         "irradiant"]]

df.head(10)

classe    age menopause tumorsize invnodes  degmalig  \
0     recurrence-events  50-59   premeno     30-34      0-2         3   
1  no-recurrence-events  50-59      ge40     40-44      0-2         3   
2  no-recurrence-events  60-69      ge40     15-19      0-2         3   
3  no-recurrence-events  50-59      ge40     10-14      0-2         2   
4  no-recurrence-events  60-69      ge40     15-19      0-2         2   
5  no-recurrence-events  30-39   premeno       5-9      0-2         2   
6     recurrence-events  50-59   premeno     25-29      0-2         2   
7  no-recurrence-events  50-59   premeno     10-14      3-5         1   
8  no-recurrence-events  60-69      lt40     30-34      0-2         1   
9  no-recurrence-events  30-39   premeno       0-4      0-2         2   

  irradiant  
0       yes  
1        no  
2       yes  
3        no  
4        no  
5        no  
6        no  
7        no  
8        no  
9        no

In [333]:
# separando campo resposta/esperado do resto do dataset

labels = df.classe
labels.head(10)

0       recurrence-events
1    no-recurrence-events
2    no-recurrence-events
3    no-recurrence-events
4    no-recurrence-events
5    no-recurrence-events
6       recurrence-events
7    no-recurrence-events
8    no-recurrence-events
9    no-recurrence-events
Name: classe, dtype: object

In [334]:
# função para converter campos em one-hot

def one_hot(categorias, valor):
    categorias = list(set(categorias))
    indice = categorias.index(valor)
    vetor = np.zeros(len(categorias))
    vetor[indice] = 1
    return vetor

# puxando quantos uniques os campos possuem para montar vetores

In [335]:
# possui 2
df.classe.unique()

array(['recurrence-events', 'no-recurrence-events'], dtype=object)

In [336]:
# possui 6
df.age.unique()

array(['50-59', '60-69', '30-39', '40-49', '70-79', '20-29'], dtype=object)

In [337]:
# possui 3
df.menopause.unique()

array(['premeno', 'ge40', 'lt40'], dtype=object)

In [338]:
# possui 11
df.tumorsize.unique()

array(['30-34', '40-44', '15-19', '10-14', '5-9', '25-29', '0-4', '20-24',
       '35-39', '50-54', '45-49'], dtype=object)

In [339]:
# possui 7
df.invnodes.unique()

array(['0-2', '3-5', '15-17', '6-8', '9-11', '12-14', '24-26'],
      dtype=object)

In [340]:
# possui 2
df.irradiant.unique()

array(['yes', 'no'], dtype=object)

# criando os one-hots

In [341]:
print(one_hot(df.classe, 'no-recurrence-events'))
print(one_hot(df.classe, 'recurrence-events'))

[1. 0.]
[0. 1.]


In [342]:
print(one_hot(df.age, '30-39'))
print(one_hot(df.age, '40-49'))
print(one_hot(df.age, '60-69'))
print(one_hot(df.age, '50-59'))
print(one_hot(df.age, '70-79'))
print(one_hot(df.age, '20-29'))

[0. 0. 0. 0. 1. 0.]
[1. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0.]
[0. 0. 1. 0. 0. 0.]
[0. 0. 0. 0. 0. 1.]


In [343]:
print(one_hot(df.menopause, 'premeno'))
print(one_hot(df.menopause, 'ge40'))
print(one_hot(df.menopause, 'lt40'))

[0. 0. 1.]
[1. 0. 0.]
[0. 1. 0.]


In [344]:
print(one_hot(df.tumorsize, '30-34'))
print(one_hot(df.tumorsize, '20-24'))
print(one_hot(df.tumorsize, '15-19'))
print(one_hot(df.tumorsize, '0-4'))
print(one_hot(df.tumorsize, '25-29'))
print(one_hot(df.tumorsize, '50-54'))
print(one_hot(df.tumorsize, '10-14'))
print(one_hot(df.tumorsize, '40-44'))
print(one_hot(df.tumorsize, '35-39'))
print(one_hot(df.tumorsize, '5-9'))
print(one_hot(df.tumorsize, '45-49'))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [345]:
print(one_hot(df.invnodes, '0-2'))
print(one_hot(df.invnodes, '6-8', ))
print(one_hot(df.invnodes, '9-11'))
print(one_hot(df.invnodes, '3-5'))
print(one_hot(df.invnodes, '15-17'))
print(one_hot(df.invnodes, '12-14'))
print(one_hot(df.invnodes, '24-26'))

[0. 0. 0. 0. 1. 0. 0.]
[0. 0. 1. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 1. 0.]
[1. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 1.]


In [346]:
print(one_hot(df.irradiant, 'no'))
print(one_hot(df.irradiant, 'yes'))

[0. 1.]
[1. 0.]


In [347]:
df.classe = [  one_hot(df.classe, _) for _ in df.classe   ]
df.age = [  one_hot(df.age, _) for _ in df.age   ]
df.menopause = [  one_hot(df.menopause, _) for _ in df.menopause   ]
df.tumorsize = [  one_hot(df.tumorsize, _) for _ in df.tumorsize   ]
df.invnodes = [  one_hot(df.invnodes, _) for _ in df.invnodes   ]
df.irradiant = [  one_hot(df.irradiant, _) for _ in df.irradiant   ]

In [348]:
df.head(10)

classe                             age        menopause  \
0  [0.0, 1.0]  [0.0, 0.0, 0.0, 1.0, 0.0, 0.0]  [0.0, 0.0, 1.0]   
1  [1.0, 0.0]  [0.0, 0.0, 0.0, 1.0, 0.0, 0.0]  [1.0, 0.0, 0.0]   
2  [1.0, 0.0]  [0.0, 1.0, 0.0, 0.0, 0.0, 0.0]  [1.0, 0.0, 0.0]   
3  [1.0, 0.0]  [0.0, 0.0, 0.0, 1.0, 0.0, 0.0]  [1.0, 0.0, 0.0]   
4  [1.0, 0.0]  [0.0, 1.0, 0.0, 0.0, 0.0, 0.0]  [1.0, 0.0, 0.0]   
5  [1.0, 0.0]  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0]  [0.0, 0.0, 1.0]   
6  [0.0, 1.0]  [0.0, 0.0, 0.0, 1.0, 0.0, 0.0]  [0.0, 0.0, 1.0]   
7  [1.0, 0.0]  [0.0, 0.0, 0.0, 1.0, 0.0, 0.0]  [0.0, 0.0, 1.0]   
8  [1.0, 0.0]  [0.0, 1.0, 0.0, 0.0, 0.0, 0.0]  [0.0, 1.0, 0.0]   
9  [1.0, 0.0]  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0]  [0.0, 0.0, 1.0]   

                                           tumorsize  \
0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
1  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, ...   
2  [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
3  [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, ...   
4  [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
5  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, ...   
6  [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
7  [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, ...   
8  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
9  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, ...   

                              invnodes  degmalig   irradiant  
0  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0]         3  [1.0, 0.0]  
1  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0]         3  [0.0, 1.0]  
2  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0]         3  [1.0, 0.0]  
3  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0]         2  [0.0, 1.0]  
4  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0]         2  [0.0, 1.0]  
5  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0]         2  [0.0, 1.0]  
6  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0]         2  [0.0, 1.0]  
7  [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]         1  [0.0, 1.0]  
8  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0]         1  [0.0, 1.0]  
9  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0]         2  [0.0, 1.0]

# normalização dos valores escalares

In [349]:
def normaliza_media(valores):
    media = np.mean(valores)
    minimo = np.min(valores)
    maximo = np.max(valores)
    return (valores - media)/(maximo-minimo)

In [350]:
df.degmalig = normaliza_media(df.degmalig)
df.head(10)

classe                             age        menopause  \
0  [0.0, 1.0]  [0.0, 0.0, 0.0, 1.0, 0.0, 0.0]  [0.0, 0.0, 1.0]   
1  [1.0, 0.0]  [0.0, 0.0, 0.0, 1.0, 0.0, 0.0]  [1.0, 0.0, 0.0]   
2  [1.0, 0.0]  [0.0, 1.0, 0.0, 0.0, 0.0, 0.0]  [1.0, 0.0, 0.0]   
3  [1.0, 0.0]  [0.0, 0.0, 0.0, 1.0, 0.0, 0.0]  [1.0, 0.0, 0.0]   
4  [1.0, 0.0]  [0.0, 1.0, 0.0, 0.0, 0.0, 0.0]  [1.0, 0.0, 0.0]   
5  [1.0, 0.0]  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0]  [0.0, 0.0, 1.0]   
6  [0.0, 1.0]  [0.0, 0.0, 0.0, 1.0, 0.0, 0.0]  [0.0, 0.0, 1.0]   
7  [1.0, 0.0]  [0.0, 0.0, 0.0, 1.0, 0.0, 0.0]  [0.0, 0.0, 1.0]   
8  [1.0, 0.0]  [0.0, 1.0, 0.0, 0.0, 0.0, 0.0]  [0.0, 1.0, 0.0]   
9  [1.0, 0.0]  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0]  [0.0, 0.0, 1.0]   

                                           tumorsize  \
0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
1  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, ...   
2  [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
3  [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, ...   
4  [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
5  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, ...   
6  [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
7  [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, ...   
8  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
9  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, ...   

                              invnodes  degmalig   irradiant  
0  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0]  0.475524  [1.0, 0.0]  
1  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0]  0.475524  [0.0, 1.0]  
2  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0]  0.475524  [1.0, 0.0]  
3  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0] -0.024476  [0.0, 1.0]  
4  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0] -0.024476  [0.0, 1.0]  
5  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0] -0.024476  [0.0, 1.0]  
6  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0] -0.024476  [0.0, 1.0]  
7  [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0] -0.524476  [0.0, 1.0]  
8  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0] -0.524476  [0.0, 1.0]  
9  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0] -0.024476  [0.0, 1.0]

In [351]:
# separando o vetor de classificação do resto do dataset
labels = df.classe.values

In [352]:
#apagando coluna do conjunto de dados
df = df.drop(['classe'], axis=1)
df.head(10)

age        menopause  \
0  [0.0, 0.0, 0.0, 1.0, 0.0, 0.0]  [0.0, 0.0, 1.0]   
1  [0.0, 0.0, 0.0, 1.0, 0.0, 0.0]  [1.0, 0.0, 0.0]   
2  [0.0, 1.0, 0.0, 0.0, 0.0, 0.0]  [1.0, 0.0, 0.0]   
3  [0.0, 0.0, 0.0, 1.0, 0.0, 0.0]  [1.0, 0.0, 0.0]   
4  [0.0, 1.0, 0.0, 0.0, 0.0, 0.0]  [1.0, 0.0, 0.0]   
5  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0]  [0.0, 0.0, 1.0]   
6  [0.0, 0.0, 0.0, 1.0, 0.0, 0.0]  [0.0, 0.0, 1.0]   
7  [0.0, 0.0, 0.0, 1.0, 0.0, 0.0]  [0.0, 0.0, 1.0]   
8  [0.0, 1.0, 0.0, 0.0, 0.0, 0.0]  [0.0, 1.0, 0.0]   
9  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0]  [0.0, 0.0, 1.0]   

                                           tumorsize  \
0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
1  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, ...   
2  [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
3  [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, ...   
4  [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
5  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, ...   
6  [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
7  [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, ...   
8  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
9  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, ...   

                              invnodes  degmalig   irradiant  
0  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0]  0.475524  [1.0, 0.0]  
1  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0]  0.475524  [0.0, 1.0]  
2  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0]  0.475524  [1.0, 0.0]  
3  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0] -0.024476  [0.0, 1.0]  
4  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0] -0.024476  [0.0, 1.0]  
5  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0] -0.024476  [0.0, 1.0]  
6  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0] -0.024476  [0.0, 1.0]  
7  [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0] -0.524476  [0.0, 1.0]  
8  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0] -0.524476  [0.0, 1.0]  
9  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0] -0.024476  [0.0, 1.0]

In [353]:
# transformar conjunto de dados em vetores, com a função abaixo

def vetorizar(age, menopause, tumorsize, invnodes, degmalig, irradiant):
    return age.tolist() + menopause.tolist() + tumorsize.tolist() + invnodes.tolist() + [degmalig] + irradiant.tolist()

In [354]:
entrada = [vetorizar(*_) for _ in df.values]
entrada

[[0.0,
  0.0,
  0.0,
  1.0,
  0.0,
  0.0,
  0.0,
  0.0,
  1.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  1.0,
  0.0,
  0.0,
  0.0,
  0.0,
  1.0,
  0.0,
  0.0,
  0.47552447552447563,
  1.0,
  0.0],
 [0.0,
  0.0,
  0.0,
  1.0,
  0.0,
  0.0,
  1.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  1.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  1.0,
  0.0,
  0.0,
  0.47552447552447563,
  0.0,
  1.0],
 [0.0,
  1.0,
  0.0,
  0.0,
  0.0,
  0.0,
  1.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  1.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  1.0,
  0.0,
  0.0,
  0.47552447552447563,
  1.0,
  0.0],
 [0.0,
  0.0,
  0.0,
  1.0,
  0.0,
  0.0,
  1.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  1.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  1.0,
  0.0,
  0.0,
  -0.02447552447552437,
  0.0,
  1.0],
 [0.0,
  1.0,
  0.0,
  0.0,
  0.0,
  0.0,
  1.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  1.0,


In [355]:
# salvando dataset formatado para uso na Classificação e labels
np.savetxt("/content/entrada_breast_cancer.csv", entrada, delimiter=',')
np.savetxt("/content/labels.csv", labels.tolist(), delimiter=',')

# Classificação

In [356]:
# importando o que é necessário
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier

In [357]:
# carregando o dataset e labels
x = np.loadtxt("/content/entrada_breast_cancer.csv", delimiter=',')
y = np.loadtxt("/content/labels.csv", delimiter=',')

In [358]:
x

array([[ 0.        ,  0.        ,  0.        , ...,  0.47552448,
         1.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.47552448,
         0.        ,  1.        ],
       [ 0.        ,  1.        ,  0.        , ...,  0.47552448,
         1.        ,  0.        ],
       ...,
       [ 0.        ,  0.        ,  0.        , ..., -0.52447552,
         0.        ,  1.        ],
       [ 0.        ,  1.        ,  0.        , ..., -0.52447552,
         1.        ,  0.        ],
       [ 1.        ,  0.        ,  0.        , ..., -0.02447552,
         0.        ,  1.        ]])

In [359]:
# criando modelo para classificação
model = KNeighborsClassifier(n_neighbors=5)

In [360]:
# separando dados para treino e validação
tamanho_treino = int(x.shape[0]*0.7)
tamanho_treino

200

In [361]:
x.shape[0] #linhas

286

In [362]:
x.shape[1] #colunas

30

In [363]:
# separando dados para treino
x_t = x[ :tamanho_treino]
y_t = y[ :tamanho_treino]

In [364]:
# separanado para validação
x_v = x[tamanho_treino: ]
y_v = y[tamanho_treino: ]

In [365]:
# criação do modelo
model.fit(x_t, y_t)

KNeighborsClassifier()

In [366]:
# performance do modelo em dados de validação
model.score(x_v, y_v)

0.6976744186046512